# Generated by Django 3.0.2 on 2020-01-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_accomodations',
            field=models.CharField(max_length=500),
        ),
    ]
